---
version: '3.3'
services:
    application:
        image: docker.pkg.github.com/nuetoban/crocodile-game-bot/crocodile:latest
        env_file: .env
        restart: on-failure
        depends_on:
            - postgresql
    postgresql:
        image: postgres:alpine
        environment:
            - postgres_password=password
        ports:
            - 5432:5432
